[package]
name = "cocacolarocks19/datasystem"
description = "A nice and easy datasystem!"
licence = "MIT"
authors = ["cocacolarocks19"]
version = "0.0.2"
registry = "https://github.com/cocacolarocks19/DataSystem"
realm = "shared"
exclude = ["rokit.toml"]

[dependencies]
